### ISSUE TITLE
error make 

### ISSUE THREAD

**Issue by gerlo99** [danog/php-libtgvoip#4]
mkdir -p shared/common
mkdir -p shared/zend
g++ -Wall -c -std=c++11 -fvisibility=hidden -DBUILDING_PHPCPP -Wno-write-strings -MD -g -fpic -o shared/common/streambuf.o common/streambuf.cpp
make: g++: Command not found
Makefile:198: recipe for target 'shared/common/streambuf.o' failed
make: *** [shared/common/streambuf.o] Error 127

**Comment by danog** [comment]
Install build-essential

**Comment by gerlo99** [comment]
In file included from zend/inivalue.cpp:8:0:
zend/includes.h:40:17: fatal error: php.h: No such file or directory
compilation terminated.
Makefile:204: recipe for target 'shared/zend/inivalue.o' failed
make: *** [shared/zend/inivalue.o] Error 1

**Comment by danog** [comment]
@gerlo99 Install php development headers

**Comment by gerlo99** [comment]
please send me the command

**Comment by danog** [comment]
@gerlo99 sudo apt install php7.version-dev

**Comment by gerlo99** [comment]
E: Unable to locate package php7.version-dev
E: Couldn't find any package by glob 'php7.version-dev'
E: Couldn't find any package by regex 'php7.version-dev'

**Comment by danog** [comment]
@gerlo99 Substitute version with your minor php version

**Comment by gerlo99** [comment]
now say this:
/usr/bin/ld: cannot find -lbfd
collect2: error: ld returned 1 exit status
Makefile:140: recipe for target 'libtgvoip.so' failed
make: *** [libtgvoip.so] Error 1

**Comment by FabianPastor** [comment]
install binutils-dev

**Comment by danog** [comment]
Or use the latest version, this is fixed now

**Comment by gerlo99** [comment]
done,but the userbot says this:
MadelineProto requires the libtgvoip extension to run. Follow the instructions @ https://voip.madelineproto.xyz to install it.

**Comment by gerlo99** [comment]
ok,now work.
thank you
