### ISSUE TITLE
Error when want to running bot MadelineProto

### ISSUE THREAD

**Issue by AyraHikari** [danog/php-libtgvoip#5]
php-libtgvoip is installed with some warnings, and when i'm going to running my bot, it got php fatal error

```
root@ubuntu:~/bot/madeline# php bot.php
PHP Fatal error:  Uncaught Please update php-libtgvoip
  thrown in MadelineProto on line 1
```

And my script is this `$MadelineProto = new \danog\MadelineProto\API('Ayra.session');`

**Comment by danog** [comment]
Whoops fixed

**Comment by danog** [comment]
(make sure to update madeline though)
